#!/bin/bash -e

if [ "${#@}" -eq 0 ]; then
    echo "setting default parameters"
    if [[ -t "0" || -p /dev/stdin ]]; then
        echo "args=up"
        # assume allocated a tty
        ARGS=(up)
    else
        echo "args=up -d"
        # no tty, so we'll run as a daemon
        ARGS=(up -d)
    fi
else
    ARGS=$@
fi

if [ -n "${FIG_FILE}"] || [ -f /opt/figapp/fig.yml ]; then
    /opt/dind/wrapdocker;
    fig $ARGS
else
    echo "No fig.yml found."
    echo ""
    echo "This image must be run with either '-v /your-fig-app:/opt/figapp',"
    echo "or you may build a dependent image using 'FROM ewindisch/figleaf',"
    echo "with a fig.yml file existing in the directory with your Dockerfile."
    echo ""
    echo "You may also refer to the documentation:"
    echo " https://github.com/ewindisch/figleaf/blob/master/README.md"
    echo ""
fi
